### ISSUE TITLE
NestedRadioButton: Typed array not recycled

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [jbvincey/NestedRadioButton#1]
In https://github.com/jbvincey/NestedRadioButton/blob/af5c8a8ce8adbd9f7d2318e328d30ff01f141bfe/nestedradiobutton/src/main/java/com/jbvincey/nestedradiobutton/NestedRadioButton.java#L71

`TypedArray attributes` should be recycled according to lint warning:

> This TypedArray should be recycled after use with #recycle()

**Comment by jbvincey** [comment]
Indeed! Nice catch, I will work on this.
Thanks for the tip.

**Comment by jbvincey** [comment]
Done, I updated the library on jcenter with the fix and gradle version update.
